# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
version: '2'
# NOTE: move this answer file up a directory so it'll work

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkinsvol:/var/jenkins_home
volumes:
  jenkinsvol:
